"""Vendor admin_id and staff_id

Revision ID: 070114280d7c
Revises: d1c15e71f703
Create Date: 2024-10-08 12:53:54.622084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070114280d7c'
down_revision = 'd1c15e71f703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('staff_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
