"""Update payment and balance

Revision ID: 37bde96d9521
Revises: a1f685367df1
Create Date: 2024-10-05 13:12:41.731206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bde96d9521'
down_revision = 'a1f685367df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
