"""JobCard attribute- quantity

Revision ID: 7ee1039da369
Revises: 6e274d223ad8
Create Date: 2024-10-12 10:52:31.567957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee1039da369'
down_revision = '6e274d223ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('quanity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quanity', sa.INTEGER(), nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
