"""Added EmploymentStatusEnum

Revision ID: 88e82640221b
Revises: 37bde96d9521
Create Date: 2024-10-05 18:01:18.561708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e82640221b'
down_revision = '37bde96d9521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_status', sa.Enum('ONGOING', 'TERMINATED', name='employmentstatusenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_column('employment_status')

    # ### end Alembic commands ###
