"""Flask-Upload added

Revision ID: f1bb0febd5ec
Revises: ca4bf87bb69b
Create Date: 2024-10-02 11:28:37.673938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bb0febd5ec'
down_revision = 'ca4bf87bb69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverynotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_file_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('delivery_file_path', sa.String(), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_file_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vat_file_path', sa.String(), nullable=True))
        batch_op.drop_column('vat_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_file', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('vat_file_path')
        batch_op.drop_column('vat_file_name')

    with op.batch_alter_table('deliverynotes', schema=None) as batch_op:
        batch_op.drop_column('delivery_file_path')
        batch_op.drop_column('delivery_file_name')

    # ### end Alembic commands ###
